Update destroy.yml

diff --git a/.github/workflows/destroy.yml b/.github/workflows/destroy.yml
--- a/.github/workflows/destroy.yml
+++ b/.github/workflows/destroy.yml
@@ -25,9 +25,6 @@ jobs:
 
       - name: Terraform Init
         run: terraform init
-
-      - name: Terraform Destroy
-        run: terraform destroy -auto-approve
      
       - name: Get EC2 Public IP
         id: get_ip
@@ -36,7 +33,14 @@ jobs:
             --filters "Name=tag:Name,Values=GitHubRunnerEC2" \
             --query "Reservations[0].Instances[0].PublicIpAddress" \
             --output text)
-          echo "ip=$IP" >> $GITHUB_OUTPUT
+          echo "Fetched EC2 IP: $IP"
+
+          # Exit if IP is empty or 'None'
+           if [ -z "$IP" ] || [ "$IP" = "None" ]; then
+           echo "ERROR: EC2 IP not found. Instance might be terminated or unreachable."
+           exit 1
+           fi 
+          echo "ip=$IP" >> $GITHUB_OUTPUT     
     
       - name: Trigger Log Parser Over SSH
         run: |
@@ -44,4 +48,6 @@ jobs:
          chmod 600 key.pem
          ssh -i key.pem -o StrictHostKeyChecking=no ubuntu@${{ steps.get_ip.outputs.ip }} \
           'sudo python3 /root/log_parser.py'
-
+      
+      - name: Terraform Destroy
+        run: terraform destroy -auto-approve
